version: '3.8'

services:
  fastapi:
    build:
      context: ./services/fastapi
      dockerfile: Dockerfile
    container_name: fastapi_container
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MLFLOW_TRACKING_URI=http://mlflow:1709
    networks:
      - app-network

  streamlit:
    build:
      context: ./services/streamlit
      dockerfile: Dockerfile
    container_name: streamlit_container
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://fastapi:8000/predict
      - FASTAPI_URL_BATCH=http://fastapi:8000/predict/batch
    depends_on:
      - fastapi
    networks:
      - app-network

  mlflow:
    build:
      context: ./services/mlflow
      dockerfile: Dockerfile
    container_name: mlflow_container
    ports:
      - "1709:1709"
    volumes:
      - mlflow_data:/app/mlruns
    networks:
      - app-network

volumes:
  mlflow_data:

networks:
  app-network:
    driver: bridge
